version: '2'

services:
      web:
            build: ./
            image: cybergrx-web
            container_name: cybergrx-web
            ports:
                  - 8080:80
                  - 8443:443
                  - 9000:9000
                  - 80:80
                  - 443:443
            volumes:
                  - ./../www/:/var/www/html
            restart: always
            environment:
                  - COMPOSE_PROJECT_NAME=cybergrx-web
            depends_on:
                  - mysql
                  - redis
            links:
                  - mysql:mysql
                  - redis:redis
      mysql:
            image: mysql:5
            container_name: cybergrx-mysql
            volumes:
                  - ./initdb.d/:/docker-entrypoint-initdb.d/
            environment:
                  MYSQL_USER: wordpress
                  MYSQL_PASSWORD: wordpress
                  MYSQL_DATABASE: wordpress
                  MYSQL_ROOT_PASSWORD: wordpress
            ports:
                  - 3306:3306
            restart: always
      redis:
            image: redis:5
            container_name: cybergrx-redis
            restart: always



