<?php /*
 * Template Name: Cyber GRX - Landing Page
 */
 ?><?php get_header(); ?><div id="wrapper"><div id="pjax__container" class="cybergrx"><?php $ua = htmlentities($_SERVER['HTTP_USER_AGENT'], ENT_QUOTES, 'UTF-8'); ?><?php if (preg_match('~MSIE|Internet Explorer~i', $ua) || (strpos($ua, 'Trident/7.0') !== false && strpos($ua, 'rv:11.0') !== false)): ?><?php $user_agent = 'user_agent__is_ie'; ?><?php else: ?><?php $user_agent = 'user_agent__is_not_ie'; ?><?php endif; ?><main id="content" class="<?php echo $user_agent; ?> bgc__white global__interactive__item__waypionts"><?php global $wp_query; ?><?php $id = get_queried_object_id(); ?><?php $prefix = '_poxy__builder__sections__'; ?><?php $group = rwmb_meta("{$prefix}group", '', $id) ? rwmb_meta("{$prefix}group", '', $id) : false; ?><?php $ptype = get_post_type($id); ?><div style="z-index:999;" class="pfxy"><?php poxy_edit(); ?></div><?php function nav__landing_page() {
?><?php global $wp_query; ?><?php $id = get_queried_object_id(); ?><?php $prefix = '_poxy__builder__sections__'; ?><?php $group = rwmb_meta("{$prefix}group", '', $id) ? rwmb_meta("{$prefix}group", '', $id) : false; ?><?php $ptype = get_post_type($id); ?><?php if(!empty($group)): ?><nav style="z-index:998;" id="nav__cybergrx__sticky" class="a14b14c12d11 paxy p2 pw2 txc__white hc hd"><div class="waxy fill bgc__navy op90 z1 bgc__orange"></div><div class="poxy xp100 a_16b_16c_16d_14"></div><ul style="border-left: rgba(255,255,255,0.0) 1px solid;" class="mw2 poxy rel z10 ms1"><div class="wcaxy x1 xp_90 bgc__white cb pn4 mn4 op60"></div><div class="_0__poxyxp100"></div><?php $count = count($group); ?><?php $c=0; foreach ( $group as $v ): $c++; ?><?php if($c != 1): ?><?php $section = isset($v["{$prefix}group__section"]) ? $v["{$prefix}group__section"] : ''; ?><?php $nav_title = isset($v["{$prefix}group__section__title"]) ? $v["{$prefix}group__section__title"] : ''; ?><?php $nav_id = isset($v["{$prefix}group__section__id"]) ? $v["{$prefix}group__section__id"] : ''; ?><?php $nav_disable = isset($v["{$prefix}group__section__menu_disable"]) ? $v["{$prefix}group__section__menu_disable"] : ''; ?><?php if(!$nav_disable): ?><?php $class = 'mn4 ms4'; ?><?php $class = ($count == $c) ? 'mn4' : $class; ?><?php $class = ($c == 0) ? 'ms4' : $class; ?><li><a href="#<?php echo $section . "__" . $nav_id; ?>" class="<?php echo $class; ?> pw2 t3 poxy xp100"><?php echo $nav_title; ?></a></li><?php endif; ?><?php endif; ?><?php endforeach; ?></ul></nav><?php endif; ?><?php }
?><?php function nav_mobile__landing_page() {
?><?php global $wp_query; ?><?php $id = get_queried_object_id(); ?><?php $prefix = '_poxy__builder__sections__'; ?><?php $group = rwmb_meta("{$prefix}group", '', $id) ? rwmb_meta("{$prefix}group", '', $id) : false; ?><?php $ptype = get_post_type($id); ?><?php if(!empty($group)): ?><section style="z-index:998;" id="section__landing_page__nav_mobile" class="ofv pfxy"><nav style="z-index:998;" id="nav__landing_page__nav_mobile" class="pbaxy rel a14b14c12d45 p2 pw2 txc__white ha hb ofv xv_100"><div class="waxy fill bgc__navy op90 z1"></div><div class="poxy xp100 a_16b_16c_16d_14"></div><button id="nav_mobile__toggle" class="eeaxy p1"><div class="paxy z1 fill bgc__navy op90"></div><div class="caxy z10 txc__white xp50 xp_50"><div id="nav_mobile__toggle__ro" class="fill"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="caxy fill"><path style="fill:#fff;" d="M8.122 24l-4.122-4 8-8-8-8 4.122-4 11.878 12z"></path></svg></div></div></button><ul style="border-left: rgba(255,255,255,0.0) 1px solid;" class="mw2 poxy rel z10 ms1"><div class="wcaxy x1 xp_90 bgc__white cb pn4 mn4 op60"></div><div class="_0__poxyxp100"></div><?php $count = count($group); ?><?php $c=0; foreach ( $group as $v ): $c++; ?><?php if($c != 1): ?><?php $section = isset($v["{$prefix}group__section"]) ? $v["{$prefix}group__section"] : ''; ?><?php $nav_title = isset($v["{$prefix}group__section__title"]) ? $v["{$prefix}group__section__title"] : ''; ?><?php $nav_id = isset($v["{$prefix}group__section__id"]) ? $v["{$prefix}group__section__id"] : ''; ?><?php $class = 'mn4 ms4'; ?><?php $class = ($count == $c) ? 'mn4' : $class; ?><?php $class = ($c == 0) ? 'ms4' : $class; ?><li><a href="#<?php echo $section . "__" . $nav_id; ?>" class="<?php echo $class; ?> pw2 t3 poxy xp100"><?php echo $nav_title; ?></a></li><?php endif; ?><?php endforeach; ?></ul></nav></section><?php endif; ?><?php }
?><?php if(!empty($group)): ?><?php $c=0; foreach ( $group as $v ): $c++; ?><?php $section = isset($v["{$prefix}group__section"]) ? $v["{$prefix}group__section"] : false; ?><?php $section_id = isset($v["{$prefix}group__section__id"]) ? $v["{$prefix}group__section__id"] : false; ?><?php $section_title = isset($v["{$prefix}group__section__title"]) ? $v["{$prefix}group__section__title"] : false; ?><?php $args = ['id' => get_queried_object_id(), 'hash' => $section_id, 'title' => $section_title ]; ?><?php $section_prefix = 'section__'; ?><?php if(substr($section, 0, strlen($section_prefix)) == $section_prefix): ?><?php $section = substr($section, strlen($section_prefix)); ?><?php endif; ?><?php if(function_exists('section__' . $section)): ?><?php if($c == 1): ?><?php nav_mobile__landing_page(); ?><?php endif; ?><?php if($c == 2): ?><section style="z-index:998;" id="section__landing_page__nav" class="ofv"><?php nav__landing_page(); ?></section><?php endif; ?><?php call_user_func('section__' . $section, $args); ?><?php endif; ?><?php endforeach; ?><?php endif; ?>

</main></div></div><?php get_footer(); ?>

